### ISSUE TITLE
Not using my base URL when publishing to Federalist

### ISSUE THREAD

**Issue by maya** [18F/jekyll_pages_api_search#35]
Search works locally but not when it's published to federalist bc it doesn't use the base URL so it doesn't work.

**Comment by jbarnicle** [comment]
@maya I believe the `{{base_url}}` is working in general, but that it is breaking search.  I'm pretty sure that is because the search form is not including the `{{ base_url }}` when composing the action for the form

https://github.com/18F/jekyll_pages_api_search/blob/master/lib/jekyll_pages_api_search/search.html

@afeld

**Comment by afeld** [comment]
This turned out to be a problem in the beta.18f.gov search template, rather than this gem. Fixed in https://github.com/18F/beta.18f.gov/commit/e96684fe0ef98f56e87c787c5e70b53f05d6a5a6.
